// Generated by CoffeeScript 1.7.1
(function() {
  var browserify;

  browserify = require('gulp-browserify');

  module.exports = function(settings) {
    return browserify(settings.browserify);
  };

}).call(this);
